modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://github.com/MattCzyr/EnderMail/issues"
license="CC BY-NC-SA 4.0"
[[mods]]
    modId="endermail"
    version="${file.jarVersion}"
    displayName="Ender Mail"
    displayURL="https://github.com/MattCzyr/EnderMail"
    authors="ChaosTheDude"
    description='''
    Employ Endermen to deliver packages anywhere in the world.
    '''
[[dependencies.endermail]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.endermail]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1]"
    ordering="NONE"
    side="BOTH"
